# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'DZNEmptyDataSet_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
#占位图
pod 'DZNEmptyDataSet'


  # Pods for DZNEmptyDataSet_Swift

  target 'DZNEmptyDataSet_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DZNEmptyDataSet_SwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
